#!/bin/bash
###############################################################################
# WP Launcher — Local Mode Installer
#
# Usage:
#   bash install-local.sh
#
# What it does:
#   1. Checks for Docker & Docker Compose
#   2. Generates .env with local mode defaults
#   3. Builds WordPress images for all PHP versions
#   4. Starts all services
#   5. Opens http://localhost in your browser
###############################################################################
set -euo pipefail

# ─── Colors ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

info()  { echo -e "${CYAN}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
err()   { echo -e "${RED}[ERROR]${NC} $*"; }
banner(){ echo -e "\n${BOLD}═══ $* ═══${NC}\n"; }

# ─── Locate project directory ────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$SCRIPT_DIR"
cd "$PROJECT_DIR"

banner "WP Launcher — Local Mode Setup"

# ─── 1. Check Docker ─────────────────────────────────────────────────────────
if ! command -v docker &>/dev/null; then
  err "Docker is not installed."
  echo "  Install Docker Desktop: https://www.docker.com/products/docker-desktop/"
  exit 1
fi
ok "Docker found ($(docker --version | head -c 40))"

if ! docker compose version &>/dev/null; then
  err "Docker Compose is not available."
  echo "  Make sure Docker Desktop is installed and running."
  exit 1
fi
ok "Docker Compose found ($(docker compose version --short))"

# Check if Docker daemon is running
if ! docker info &>/dev/null 2>&1; then
  err "Docker daemon is not running. Please start Docker Desktop."
  exit 1
fi
ok "Docker daemon is running"

# ─── 2. Generate .env ────────────────────────────────────────────────────────
banner "Configuring Environment"

gen_secret() {
  # Works on all platforms (no openssl required)
  head -c 32 /dev/urandom 2>/dev/null | base64 | tr -d '/+=' | head -c 40 || \
  python3 -c "import secrets; print(secrets.token_urlsafe(30))" 2>/dev/null || \
  echo "local-dev-$(date +%s)-$(( RANDOM * RANDOM ))"
}

if [ -f "$PROJECT_DIR/.env" ]; then
  # Check if it's already local mode
  if grep -q "APP_MODE=local" "$PROJECT_DIR/.env" 2>/dev/null; then
    ok ".env already configured for local mode"
  else
    warn ".env exists but is not set to local mode."
    echo -n "  Overwrite with local mode config? (y/N): "
    read -r OVERWRITE
    if [ "$OVERWRITE" != "y" ] && [ "$OVERWRITE" != "Y" ]; then
      info "Keeping existing .env. Make sure APP_MODE=local is set."
    else
      rm "$PROJECT_DIR/.env"
    fi
  fi
fi

if [ ! -f "$PROJECT_DIR/.env" ]; then
  API_KEY="$(gen_secret)"
  JWT_SECRET="$(gen_secret)"
  PROVISIONER_KEY="$(gen_secret)"

  cat > "$PROJECT_DIR/.env" <<ENVFILE
# WP Launcher — Local Mode
# Generated by install-local.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")

APP_MODE=local
NODE_ENV=development

# Domain (*.localhost resolves to 127.0.0.1 in modern browsers)
BASE_DOMAIN=localhost
PUBLIC_URL=http://localhost

# Secrets (auto-generated)
API_KEY=${API_KEY}
JWT_SECRET=${JWT_SECRET}
PROVISIONER_INTERNAL_KEY=${PROVISIONER_KEY}
JWT_EXPIRES_IN=30d

# No limits in local mode
MAX_SITES_PER_USER=0
MAX_TOTAL_SITES=0

# No resource limits for local containers
CONTAINER_MEMORY=0
CONTAINER_CPU=0

# WordPress image
WP_IMAGE=wp-launcher/wordpress:latest

# SMTP (Mailpit — catches all emails locally)
SMTP_HOST=mailpit
SMTP_PORT=1025
SMTP_SECURE=false
SMTP_FROM=WP Launcher <noreply@localhost>
ENVFILE

  chmod 600 "$PROJECT_DIR/.env"
  ok ".env created with local mode defaults"
fi

# ─── 3. Create data directory ────────────────────────────────────────────────
mkdir -p "$PROJECT_DIR/data"
ok "Data directory ready"

# ─── 4. Build WordPress images ───────────────────────────────────────────────
banner "Building WordPress Images"
info "Building images for PHP 8.1, 8.2, and 8.3..."
info "This may take a few minutes on the first run."
echo ""

bash "$PROJECT_DIR/scripts/build-wp-image.sh"
ok "All WordPress images built"

# ─── 5. Install wpl CLI command ───────────────────────────────────────────────
banner "Installing CLI"

chmod +x "$PROJECT_DIR/bin/wpl"

WPL_INSTALLED=false

# Try standard locations in order of preference
if [ -d "/usr/local/bin" ] && [ -w "/usr/local/bin" ]; then
  ln -sf "$PROJECT_DIR/bin/wpl" /usr/local/bin/wpl
  ok "Installed 'wpl' command to /usr/local/bin/wpl"
  WPL_INSTALLED=true
elif [ -d "$HOME/.local/bin" ]; then
  ln -sf "$PROJECT_DIR/bin/wpl" "$HOME/.local/bin/wpl"
  ok "Installed 'wpl' command to ~/.local/bin/wpl"
  WPL_INSTALLED=true
elif [ -d "$HOME/bin" ]; then
  ln -sf "$PROJECT_DIR/bin/wpl" "$HOME/bin/wpl"
  ok "Installed 'wpl' command to ~/bin/wpl"
  WPL_INSTALLED=true
else
  # Create ~/.local/bin and add to PATH
  mkdir -p "$HOME/.local/bin"
  ln -sf "$PROJECT_DIR/bin/wpl" "$HOME/.local/bin/wpl"
  # Add to shell profile if not already there
  SHELL_RC=""
  if [ -f "$HOME/.bashrc" ]; then SHELL_RC="$HOME/.bashrc"
  elif [ -f "$HOME/.zshrc" ]; then SHELL_RC="$HOME/.zshrc"
  elif [ -f "$HOME/.profile" ]; then SHELL_RC="$HOME/.profile"
  fi
  if [ -n "$SHELL_RC" ] && ! grep -q '.local/bin' "$SHELL_RC" 2>/dev/null; then
    echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$SHELL_RC"
    info "Added ~/.local/bin to PATH in $SHELL_RC"
    info "Run 'source $SHELL_RC' or open a new terminal for 'wpl' to work."
  fi
  ok "Installed 'wpl' command to ~/.local/bin/wpl"
  WPL_INSTALLED=true
fi

if [ "$WPL_INSTALLED" = false ]; then
  warn "Could not install 'wpl' globally. You can run it directly:"
  echo "  $PROJECT_DIR/bin/wpl help"
fi

# ─── 6. Start services ──────────────────────────────────────────────────────
banner "Starting Services"

docker compose up -d --build
ok "All services started!"

# Wait a moment for services to be ready
info "Waiting for services to initialize..."
sleep 3

# Quick health check
if curl -sf http://localhost/api/settings > /dev/null 2>&1; then
  ok "API is responding"
elif curl -sf http://localhost:3000/api/settings > /dev/null 2>&1; then
  ok "API is responding (port 3000)"
else
  warn "API may still be starting up — give it a few more seconds"
fi

# ─── 7. Summary ──────────────────────────────────────────────────────────────
banner "Setup Complete!"

echo -e "${GREEN}${BOLD}"
echo "  WP Launcher (Local Mode) is running!"
echo ""
echo "  Dashboard:  http://localhost"
echo "  Mailpit:    http://localhost:8025"
echo ""
echo "  Sites will be available at: http://{subdomain}.localhost"
echo -e "${NC}"
echo ""
echo "  Quick start:"
echo "    1. Open http://localhost (or run: wpl open)"
echo "    2. Click '+ Create Site'"
echo "    3. Choose your settings and click 'Create Site'"
echo "    4. Your WordPress site will be ready in ~15 seconds"
echo ""
echo "  Commands (run from anywhere):"
echo "    wpl start                        # Start WP Launcher"
echo "    wpl stop                         # Stop WP Launcher"
echo "    wpl restart                      # Restart all services"
echo "    wpl status                       # Show running containers"
echo "    wpl logs [service]               # Tail logs"
echo "    wpl open [subdomain]             # Open site in browser"
echo "    wpl shell <subdomain>            # Bash into a site container"
echo "    wpl wp <subdomain> plugin list   # Run WP-CLI commands"
echo "    wpl help                         # Show all commands"
echo ""
echo -e "${YELLOW}  Note: *.localhost domains work in Chrome, Firefox, and Edge."
echo -e "  Safari users may need to add entries to /etc/hosts.${NC}"
echo ""

# Try to open browser
if command -v xdg-open &>/dev/null; then
  xdg-open "http://localhost" 2>/dev/null &
elif command -v open &>/dev/null; then
  open "http://localhost" 2>/dev/null &
elif command -v start &>/dev/null; then
  start "http://localhost" 2>/dev/null &
fi
