api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: wp-launcher-network
    watch: true

  file:
    directory: "/etc/traefik/dynamic"
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: "${ACME_EMAIL:-admin@localhost}"
      storage: /acme/acme.json
      httpChallenge:
        entryPoint: web

  httpchallenge:
    acme:
      email: "${ACME_EMAIL:-admin@localhost}"
      storage: /acme/acme-http.json
      httpChallenge:
        entryPoint: web

log:
  level: DEBUG

accessLog: {}
